version: 2
jobs:
  build:
    machine:
      image: node:16-buster 
      docker_layer_caching: true
      working_directory: $SOURCE
    steps:
      - checkout
      - run: 
         name: todo
         command: docker build -t todo:1.0.2 .
workflows:
  build_and_test:
    jobs:
      - build
