version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
 build:
   docker:
     - image: docker
   steps:
     - checkout
     - setup_remote_docker:
          docker_layer_caching: true
     - run: docker images ls
     - run: ls
     - run: cd /todo
     - run: ls
     - run: echo $SOURCE
workflows:
    todo:
      jobs:
        - build
