version: 2
jobs:
  build:
    docker:
      # - image: cimg/<language>:<version TAG>
      #   auth:
      #     username: $DOCKERHUB_USERNAME
      #     password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run: docker build -t todo:1.0.2 .
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
