version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
 build:
   docker:
      - image: docker
   dependencies:
     pre:
      - rm -rf ~/.yarn
      - npm install -g yarn
      - yarn -v
     override:
      - yarn
     cache_directories:
      - ~/.cache/yarn
   steps:
     - checkout
     - setup_remote_docker:
          docker_layer_caching: true
     - run: ls
     - run: pwd
     - run: docker build -t todo ./$SOURCE
     - run: docker images ls

workflows:
    build:
      jobs:
        - build:
           context: react-js
