version: 2.1
orbs:
   node: circleci/node@4.7.0
jobs:
 build:
   docker:
      - image: cimg/node:17.0.1
   steps:
     - checkout
     - setup_remote_docker:
          docker_layer_caching: true
     - run: yarn --version
     - run: yarn --cwd ./$SOURCE
     - run: yarn --cwd ./$SOURCE build --profile
     - run: ls
     #- run: yarn
     #- run: yarn build --profile
     # - run: docker build -t todo ./$SOURCE
     # - run: docker images ls

workflows:
    build:
      jobs:
        - build:
           context: react-js
